// ReplateQuest Contract ABI for frontend
// Update CONTRACT_ADDRESS after deployment

export const CONTRACT_ADDRESS = "0xb9b7BD63E098ABd55605312933899fC4f3EF59F8" as const;

// Contract constants
export const CONTRACT_CONSTANTS = {
  FEE: 1e6, // 1 USDC (6 decimals)
  DAILY_FRUIT_VEG_PER_PERSON: 300, // grams
  MIN_HEALTHY_SCORE: 60,
  BASE_POINTS: 50,
  STREAK_BONUS: 25,
  CHECKIN_POINTS: 10,
} as const;

// Phase enum
export const Phase = {
  FREE: 0,
  PAID: 1,
} as const;

// ABI is imported from typechain-types generated by Hardhat
// Run `npm run compile` to regenerate typechain-types
import { ReplateQuest__factory } from "../../typechain-types";
export const REPLATE_QUEST_ABI = ReplateQuest__factory.abi;
