ALTER TABLE canonical_products
  ADD COLUMN IF NOT EXISTS gtin TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS brand TEXT,
  ADD COLUMN IF NOT EXISTS quantity TEXT,
  ADD COLUMN IF NOT EXISTS ingredients TEXT,
  ADD COLUMN IF NOT EXISTS allergens TEXT,
  ADD COLUMN IF NOT EXISTS additives TEXT,
  ADD COLUMN IF NOT EXISTS nutrition_grade TEXT,
  ADD COLUMN IF NOT EXISTS nova_group SMALLINT,
  ADD COLUMN IF NOT EXISTS energy_kcal NUMERIC,
  ADD COLUMN IF NOT EXISTS protein NUMERIC,
  ADD COLUMN IF NOT EXISTS carbohydrates NUMERIC,
  ADD COLUMN IF NOT EXISTS sugar NUMERIC,
  ADD COLUMN IF NOT EXISTS fat NUMERIC,
  ADD COLUMN IF NOT EXISTS saturated_fat NUMERIC,
  ADD COLUMN IF NOT EXISTS fiber NUMERIC,
  ADD COLUMN IF NOT EXISTS salt NUMERIC,
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'replate',
  ADD COLUMN IF NOT EXISTS source_confidence NUMERIC(5,4) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS data_completeness NUMERIC(5,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS user_product_scans (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_wallet TEXT,
  product_id BIGINT REFERENCES canonical_products(id) ON DELETE SET NULL,
  gtin TEXT NOT NULL,
  source TEXT NOT NULL,
  scan_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS user_product_scans_wallet_time
  ON user_product_scans (LOWER(user_wallet), scan_timestamp DESC);
